### ISSUE TITLE
denox on deno 1.7.5

### ISSUE THREAD

**Issue by Cyberhan123** [BentoumiTech/denox#28]
## 【Bug】deno throw error

- Bug Report

`
Check https://denopkg.com/BentoumiTech/denox/denox.ts
error: TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { ParseOptions, parse, parseAll } from "./yaml/parse.ts";
         ~~~~~~~~~~~~
    at https://deno.land/std@0.42.0/encoding/yaml.ts:6:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  DumpOptions as StringifyOptions,
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.42.0/encoding/yaml.ts:8:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  DenoWorkspace,
  ~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/BentoumiTech/denox/master/src/interfaces.ts:25:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  WorkspaceGlobal,
  ~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/BentoumiTech/denox/master/src/interfaces.ts:26:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  WorkspaceScript,
  ~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/BentoumiTech/denox/master/src/interfaces.ts:27:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  WorkspaceOptions,
  ~~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/BentoumiTech/denox/master/src/interfaces.ts:28:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  DenoOptionsEntries,
  ~~~~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/BentoumiTech/denox/master/src/interfaces.ts:29:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  DenoOptionValue,
  ~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/BentoumiTech/denox/master/src/interfaces.ts:30:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { getOptionType, OptionTypeValues };
                        ~~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/BentoumiTech/denox/master/src/deno_options/utils.ts:40:25

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { buildDenoCLIOptionsArgs, CLIArgument };
                                  ~~~~~~~~~~~
    at https://raw.githubusercontent.com/BentoumiTech/denox/master/src/deno_options/build_cli_arguments.ts:75:35

Found 10 errors.

`

## Info

- DenoX version: @last version

**Comment by Cyberhan123** [comment]
@BentoumiTech please update ts export type https://deno.land/manual@v1.7.5/typescript/faqs#why-are-you-forcing-me-to-use-isolated-modules-why-can#39t-i-use-const-enums-with-deno-why-do-i-need-to-do-export-type

**Comment by fangmarks** [comment]
Any updates on when the fix for this would get published?
I wanted to install denox but I'm also getting these errors

**Comment by Cyberhan123** [comment]
> Any updates on when the fix for this would get published?
> I wanted to install denox but I'm also getting these errors

U can use my fixed  , it's an unstable way to reslove this question.
```
deno install -Af -n denox https://raw.githubusercontent.com/Cyberhan123/denox/@0.4.2/denox.ts
```

**Comment by angelhdzmultimedia** [comment]
When the fix? First time I used this package it worked like a charm, and now that I decided to make a whole project it broke...

**Comment by Cyberhan123** [comment]
@angelhdz I find one https://deno.land/x/denon@2.4.7

**Comment by fangmarks** [comment]
Denon is not the same as Denox. 

Denon is the Deno version of nodemon, whereas Denox basically combines docker-compose files with node's npm scripts

**Comment by Cyberhan123** [comment]
> 天龙与Denox不同。
> 
> Denon是nodemon的Deno版本，而Denox基本上将docker-compose文件与node的npm脚本结合在一起

But have same fatures

**Comment by fangmarks** [comment]
I'm getting this Error again on `Deno v1.10.2` after trying to install denox like this `deno install -Af -n denox https://denopkg.com/BentoumiTech/denox/denox.ts`
